### ISSUE TITLE
Comment out Pods (CocoaPods) directory by default

### ISSUE THREAD

**Issue by tangestani** [dvcs/gitignore#46]
It would make more sense to have this directory commented out by default.

The general consensus seems to be that this directory should be included in source control in most cases, unless the size of the directory makes pushing noticeably slower.

The CocoaPods team lay out the pros and cons along with their recommendation to include it in source control [here](https://guides.cocoapods.org/using/using-cocoapods.html#should-i-check-the-pods-directory-into-source-control).

**Comment by joeblau** [comment]
This template is specifically for Cocoapods... commenting out the only line in the template defeats the point.

If you don't want to use Cocoapods, you don't have to even include this template.

**Comment by tangestani** [comment]
You've got a point, it's kind of weird having the whole Cocoapods template be commented out. The problem is that there doesn't seem to be a way to request the Swift template from the gitignore.io API without pulling the Cocoapods template along with it.

**Comment by joeblau** [comment]
Yeah, I'm working on that right now.  One of the problems with the way @github currently hosts their templates is that there is now way to compose them.  One of the goals of my [dvcs/gitignore](https://github.com/dvcs/gitignore) project is to allow for composition and extensions of templates (with only the filesystem which is hard).  Due to GitHub's limitation, I'm putting together a blog post where I'm going to declare a permanent fork from GitHub's list.

You should be able to specify Cocoapods as a separate template like and that's where we're going in the new world order.

gi swift,cocopaods
